# Generated by Django 4.2.5 on 2025-03-29 06:13

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="order",
            field=courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
