# Generated by Django 5.0.4 on 2024-04-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_module_created_module_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="description",
        ),
    ]
