# Generated by Django 4.2.5 on 2025-04-01 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_slug_alter_course_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="slug",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
