# Generated by Django 4.2.5 on 2025-04-01 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_module_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="slug",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
