# Generated by Django 4.2.5 on 2025-04-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_content_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="owner",
        ),
    ]
