# Generated by Django 4.2.5 on 2025-05-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_remove_content_owner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Enrollment",
        ),
    ]
