# Generated by Django 4.2.5 on 2025-05-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("COMPLETED", "Completed"),
                    ("IN PROGRESS", "In progress"),
                    ("REACHED DEADLINE", "reached deadline"),
                ],
                default="IN PROGRESS",
            ),
        ),
    ]
